### ISSUE TITLE
ImportFromPath exec errors out

### ISSUE THREAD

**Issue by abake48** [BuvinJT/distbuilder#1]
https://github.com/BuvinJT/distbuilder/blob/3e38987984cdb762fa2d6dcf4f3a2b5d83699bee/distbuilder/util.py#L490

Appending to the end of sysPath resulted in an "Invalid Command Name" error when calling exec().
Prepending the scriptDir to the sysPath proved to be a working solution for now.

**Comment by BuvinJT** [comment]
Thanks!  That is a context dependent glitch.  It works fine to append to the syspath in most situations, but prepending to the path would, in fact, be the correct way to write that code!  The function should always work if written like that.

**Comment by BuvinJT** [comment]
To submit a patch for this: 

- Create a fork (a personal copy of the repo)

https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo

- Create a branch on your fork, with your patch

- Submit a pull request on this project, for that fork/branch

https://guides.github.com/activities/hello-world/#pr

https://github.com/BuvinJT/distbuilder/pulls
